name: Cache Demo

on:
  workflow_dispatch:

jobs:
  cache-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache Apt Packages
        uses: actions/cache@v4
        with:
          path: /var/cache/apt
          key: apt-cache-${{ runner.os }}

      - name: Install Tree
        run: |
          sudo apt-get update
          sudo apt-get install -y tree

      - name: Verify Tree
        run: tree --version
