name: Run Real Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Make Script Executable
        run: chmod +x scripts/test.sh

      - name: Run Test Script
        run: ./scripts/test.sh
