name: Schedule Workflow

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  backup-job:
    runs-on: ubuntu-latest

    steps:
      - name: Daily Message
        run: echo "This workflow runs every day at midnight UTC"